# Generated by Django 3.1.1 on 2020-09-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noodle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('metadata', models.JSONField(null=True)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='NoodleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='django_images/')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('noodle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rameniaapp.noodle')),
            ],
        ),
        migrations.AddField(
            model_name='noodle',
            name='tags',
            field=models.ManyToManyField(to='rameniaapp.Tag'),
        ),
    ]
