# Generated by Django 3.1.1 on 2020-09-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noodle',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noodle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rameniaapp.Tag'),
        ),
        migrations.AlterField(
            model_name='noodleimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
