# Generated by Django 3.1.1 on 2020-09-28 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0004_badge_noodlereport_profile_profilereport_report_review_reviewimages_reviewreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='noodle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rameniaapp.noodle'),
        ),
    ]
