# Generated by Django 3.1.1 on 2020-09-28 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0005_review_noodle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='noodle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rameniaapp.noodle'),
        ),
    ]
