# Generated by Django 3.1.1 on 2020-09-28 00:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rameniaapp', '0007_auto_20200928_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewImages',
            new_name='ReviewImage',
        ),
    ]
