# Generated by Django 3.1.1 on 2020-10-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0010_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='noodleimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
