# Generated by Django 3.1.1 on 2020-10-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0012_auto_20201009_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='noodle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rameniaapp.noodle'),
        ),
    ]
