# Generated by Django 3.1.1 on 2020-10-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0015_auto_20201012_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
