# Generated by Django 3.1.2 on 2020-10-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0016_auto_20201013_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramen',
            name='ramen_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
