# Generated by Django 3.1.2 on 2020-10-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0016_auto_20201013_2359'),
        ('rameniaapp', '0016_auto_20201015_0207'),
        ('rameniaapp', '0016_auto_20201015_1928'),
    ]

    operations = [
    ]
