# Generated by Django 3.1.2 on 2020-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0016_auto_20201015_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='rameniaapp.Profile'),
        ),
    ]
