# Generated by Django 3.1.1 on 2020-10-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0017_profile_following'),
        ('rameniaapp', '0016_auto_20201015_0207'),
    ]

    operations = [
    ]
