# Generated by Django 3.1.2 on 2020-10-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0017_merge_20201019_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ramen',
        ),
    ]
