# Generated by Django 3.1.1 on 2020-10-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0018_merge_20201029_0154'),
        ('rameniaapp', '0018_delete_ramen'),
    ]

    operations = [
    ]
