# Generated by Django 3.1.1 on 2020-10-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0019_merge_20201030_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
