# Generated by Django 3.1.2 on 2020-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0020_auto_20201030_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_name', models.CharField(max_length=80)),
                ('params', models.JSONField()),
            ],
        ),
    ]
