# Generated by Django 3.1.1 on 2020-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0021_actionhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noodleimage',
            name='image',
            field=models.ImageField(default='noodle.png', upload_to=''),
        ),
    ]
