# Generated by Django 3.1.1 on 2020-11-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0022_auto_20201110_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noodleimage',
            name='image',
            field=models.ImageField(default='noodles.png', upload_to=''),
        ),
    ]
