# Generated by Django 3.1.1 on 2020-11-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0023_auto_20201110_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='noodleimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
