# Generated by Django 3.1.1 on 2020-11-11 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0024_noodleimage_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noodle',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='edit',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noodle',
            name='created_timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='noodle',
            name='edited_timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='noodleimage',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
