# Generated by Django 3.1.3 on 2020-11-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0022_review_created'),
        ('rameniaapp', '0024_noodleimage_is_default'),
    ]

    operations = [
    ]
