# Generated by Django 3.1.3 on 2020-11-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rameniaapp', '0025_merge_20201111_0209'),
        ('rameniaapp', '0025_auto_20201111_0620'),
    ]

    operations = [
    ]
